LOAD DATA LOCAL INFILE :file INTO TABLE {0}  FIELDS TERMINATED BY  {1} ENCLOSED BY {2} LINES TERMINATED BY {3}   IGNORE 1 LINES 
 SET memDob = STRING_TO_DATE  (SUBSTRING(memDob,1,25)) , runndate =STRING_TO_DATE(SUBSTRING(runndate,1,25)),  paiddate=STRING_TO_DATE(SUBSTRING(paiddate,1,25))
 