
insert into membership_level_claim_summary select :insId,:fileId, :activityMonth, IPA_CD, IPANAME, PCP_PROVIDER_NBR, PCPFIRSTNAME, PCPLASTNAME, CONTRACT_YR, 
TIME_PERIOD, RISK_ENTITY_TYPE, EFFECTIVE_DT, EXPIRATION_DT, TRACK_MODEL, RISK_FLAG, ACTIVITYDATE, ACTIVITYMONTH, SRC_SYS_MEMBER_NBR, MLNAME, MFNAME, MBRDOB, 
MBRGENDER, MEDICAIDNO, MEDICARENO, MEMBER_MONTH_CNT, HIC_NUMBER, HOSPICE, ESRD, AGED_DISABLED_MSP, INSTITUTIONAL, NHC, MEDICAID_FLAG, LTI_FLAG, MEDICAID_INDICATOR,
RISK_ADJUSTER_FACTOR_A, PART_D_RA_FACTOR, LIS_PREMIUM_SUBSIDY, PREMIUM_REBATE_PARTD_AMOUNT, PART_D_SUBSIDY_PAYMENT_AMOUNT, TOTAL_MA_PAYMENT_AMOUNT, 
TOTAL_MB_PAYMENT_AMOUNT, TOTAL_PART_D_PAYMENT, PART_D_IND, PREMIUM, OB_KICK_PREMIUM, NEWBORN_KICK_PREMIUM, NICU_KICK_PREMIUM, LOW_BIRTH_KICK_PREMIUM, 
EXCESS_NICU_REV, FUNDING, INST_CLAIMS, PROF_CLAIMS, PHAR_CLAIMS, STOPLOSS_RATE, STOPLOSS_CHARGE, STOPLOSS_CREDIT_AMT, STOPLOSS_CREDIT, STOPLOSS_THRESHOLD, 
STOPLOSS_CREDIT_PCT, PREMIUM_TAX, VAB_ADJUSTMENT, MCO_ADMIN_FEE, MEF_PCT, MEFSHAREAMOUNT, MEF_BALANCE_SHARE, PRODUCT_LABEL, PRODUCT_LVL1, PRODUCT_LVL2, PRODUCT_LVL3,
PRODUCT_LVL4, PRODUCT_LVL5, PRODUCT_LVL6, PRODUCT_LVL7, MARKET_LVL1, MARKET_LVL2, MARKET_LVL3, MARKET_LVL4, MARKET_LVL5, MARKET_LVL6, MARKET_LVL7, MARKET_LVL8, 
CAPITATION_DENTAL, CAPITATION_PCP, CAPITATION_SPECIALIST, CAPITATION_TRANSPORTATION, CAPITATION_VISION, IBNR_INST, IBNR_PROF, IBNR_TOT, FINANCE_RESERVE_RATE, 
FINANCE_RESERVE_TYPE, FINANCE_RESERVE_AMOUNT, TIN 
from csv2table_amg_member_level ml



