   replace into  simply_mmr  select null,:activityMonth reportMonth,:insId insId, c.prvdr_id, mbr_id, :fileId,   
  IPA, SubIPA, QNXTMemberID, MemberName, EnrollID, PlanID, ProgramID, ContractID, MedicaidNumber, HICN, Gender, DateofBirth, CountyCode, PcpId, PcpName, Activity_Date, HIC_Number, Payment_Adj_MSA_Start_Date, Payment_Adj_MSA_End_Date, Risk_Adjuster_Paymnt_Adj_Rate_A, Risk_Adjuster_Paymnt_Adj_Rate_B, PACE_Premium_AddOn, PACE_Cost_Sharing_AddOn, Demographic_Paymnt_Adj_Rate_A, Demographic_Paymnt_Adj_Rate_B, LIS_Premium_Subsidy, MSA_Part_A_Deposit_Recovery_Amt, MSA_Part_B_Deposit_Recovery_Amt, Part_C_Basic_Premium_Part_A, Part_C_Basic_Premium_Part_B, Rbt_Part_A_CostSharing_Reduction, Rbt_Part_B_CostSharing_Reduction, Rbt_Other_Part_A_ManSupplBenefit, Rbt_Other_Part_B_ManSupplBenefit, Rbt_Part_B_PremReduction_Part_A, Rbt_Part_B_PremReduction_Part_B, Rbt_Part_D_SupplBenefits_Part_A, Rbt_Part_D_SupplBenefits_Part_B, Total_Part_A_MA_Payment, Total_Part_B_MA_Payment, Total_MA_Payment, Rebate_Part_DBasicPremium_Reduct, Part_D_Basic_Premium_Amt, Part_D_DirectSubsidy_Payment_Amt, Reinsurance_Subsidy_Amt, LowIncomeSubsidyCostsharing_Amt, Total_Part_D_Payment, Surname, First_initial, Sex, Date_of_Birth, Age_Group, State_and_County_code, Out_of_Area_Indicator, Part_A_Entitlement, Part_B_Entitlement, Hospice, ESRD, Aged_Disabled_MSP, Institutional, NHC, New_Medicare_Bene_Medicaid_Flag, LTI_Flag, Medicaid_Indicator, Default_Risk_Factor_Code, Risk_Adjuster_Factor_A, Risk_Adjuster_Factor_B, ESRD_MSP_Flag, Bene_Current_Medicaid_Status, Risk_Adjuster_Age_Group_RAAG, DeMinimis, Plan_Benefit_Package_ID, RA_Factor_Type_Code, Frailty_Indicator, OriginalReasonEntitlement, Enrollment_Source, EGHP_Flag, Part_D_RA_Factor, Part_D_LowIncome_Indicator, Part_D_LowIncome_Multiplier, Part_D_Long_Term_Inst_Indicator, Part_D_Long_Term_Inst_Multiplier
  ,now() created_date,now() updated_date, :username created_by,:username updated_date, 'Y' active
  from csv2table_simply_mmr  ml
 LEFT JOIN  ( select c.*,rc.insurance_id,rc.prvdr_id from contract c 
                         JOIN reference_contracts rc on  c.contract_Id = rc.contract_Id  and insurance_id =:insId
 				 ) c on FIND_IN_SET(ml.PcpId, c.PCP_PROVIDER_NBR)
 left join membership m on m.Mbr_MedicaidNo =    MedicaidNumber  ;
  
  