insert into provider_adjustment select :insId,:fileId, :activityMonth, IPA_CD, RISK_ENTITY_TYPE, CONTRACT_YEAR, TIME_PERIOD, CONTRACT_PERIOD_START_DT, 
CONTRACT_PERIOD_END_DT, TRACK_MODEL, RISK_IND, PCP_PROVIDER_NBR, ACTIVITYDATE, ACTIVITYMONTH, RISK_RECON_COS_DESC, ADJUSTMENT_DESC, PRODUCT_LABEL, PRODUCT_LVL1, 
PRODUCT_LVL2, PRODUCT_LVL3, PRODUCT_LVL4, PRODUCT_LVL5, PRODUCT_LVL6, PRODUCT_LVL7, MARKET_LVL1, MARKET_LVL2, MARKET_LVL3, MARKET_LVL4, MARKET_LVL5, MARKET_LVL6,
MARKET_LVL7, MARKET_LVL8, ADJUSTMENT_AMT, TIN
from csv2table_amg_adjust ml



