LOAD DATA LOCAL INFILE :file ignore INTO TABLE {0}  FIELDS TERMINATED BY  {1} ENCLOSED BY {2} LINES TERMINATED BY {3}   IGNORE 1 LINES  set PCP_PROVIDER_NBR = convert(PCP_PROVIDER_NBR,unsigned)
,CONTRACT_PERIOD_START_DT=STRING_TO_DATE(CONTRACT_PERIOD_START_DT), CONTRACT_PERIOD_END_DT =STRING_TO_DATE(CONTRACT_PERIOD_END_DT)
,ACTIVITYDATE=STRING_TO_DATE(ACTIVITYDATE)
